hdac-io/friday

cmd/nodef/genesiscmd.go, x/executionlayer/configuration/chainspec_test.go, x/executionlayer/genesis.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/types/genesis.go, x/executionlayer/types/genesis_test.go
if load-chainspec is executed after add-el-genesis-account, load-chainspec cmd would overwrite accounts with null in executionlayer in genesis.json.
fix the problem by separating Accounts from GenesisConf.
=> fix: load-chainspec overwrites accounts

Makefile
Now we can see the version of binaries by
$ nodef version
$ clif version
The version belongs to latest git tag.
=> add build flag for versioning

README.md, server/util.go
In the beginning of our tx could have wasm binary which has about 2Mib plus alpha bytes data.
So we need to enlarge our bytes' limitation.
This patch affects default config.toml file.
=> set max tx bytes and body bytes to 3MiB

README.md, app/app.go, client/flags/flags.go, cmd/clif/main.go, x/executionlayer/alias.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/root.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/module.go, x/executionlayer/querier.go, x/executionlayer/test_common.go, x/executionlayer/types/codec.go, x/executionlayer/types/msgs.go, x/executionlayer/util.go
* Detaching bank module from EE
* Add 'create account' logic if recipient account doesn't exist
* Inserted `token_owner_address` for later use in request message
* Restore transfer logic inside of keeper
* `makeEETransferMsg` in bank account still remains in case of emergency
=> Add new account logic & detach bank module from EE

cmd/nodef/genesiscmd.go, tests/resources/executionlayer/genesis/genesis_with_invalid_wasm_path.toml, tests/resources/executionlayer/genesis/genesis_with_missing_field.toml, tests/resources/executionlayer/genesis/manifest.toml, x/executionlayer/configuration/chainspec.go, x/executionlayer/configuration/chainspec_test.go, x/executionlayer/genesis.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/resources/manifest.toml, x/executionlayer/test_common.go, x/executionlayer/types/genesis.go
remove genesis.name field in chainspec toml
and use chain_id as chain name for the execution engine.
=> feat: unify chain name in config

README.md, app/app.go, cmd/nodef/main.go, go.mod, go.sum, x/auth/client/utils/tx.go, x/executionlayer/abci.go, x/executionlayer/alias.go, x/executionlayer/client/cli/flags.go, x/executionlayer/client/cli/root.go, x/executionlayer/client/cli/tx.go, x/executionlayer/genesis.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/module.go, x/executionlayer/types/codec.go, x/executionlayer/types/errors.go, x/executionlayer/types/key.go, x/executionlayer/types/msgs.go, x/executionlayer/types/types.go, x/executionlayer/types/validator.go, x/executionlayer/types/validator_test.go, x/genutil/client/cli/gentx.go, x/genutil/collect.go, x/genutil/types/codec.go, x/genutil/types/genesis_state.go, x/staking/module.go
Feat:
- add to create-validator cli
- connect to bond, unbond logic in blockchain
- separate store eeState & validator
- remove to unnecessary module when begin, end block
- add to candidate block state
Caution: (Need to fix and more check..)
- bond amount must be lower than 7_000_000 (If more than this amount, ee returns "Interpreter(Trap(Trap { kind: Host(GasLimit) }))"
- need to delete to add-genesis-account + delete to stake module in gentx
=> feat: support to stake

README.md, go.mod, go.sum, scripts/install_casperlabs_ee.sh, tests/resources/executionlayer/genesis/manifest.toml, x/executionlayer/configuration/chainspec.go, x/executionlayer/configuration/chainspec_test.go, x/executionlayer/genesis.go, x/executionlayer/keeper.go, x/executionlayer/resources/manifest.toml, x/executionlayer/types/errors.go, x/executionlayer/types/genesis.go, x/executionlayer/types/genesis_test.go
- Version up v0.10.0
-- add to deploy config in genesis
-- remove wasm validate function
-- change to using the system contract default path just like any other contract. (need to change when creating integrated test later)
- removed utility dependencies when execute grpc error handling to effectively handle multiple deploys
- handling wasm execute error
=> Support to execution engine v0.10.0

x/executionlayer/client/cli/tx.go, x/executionlayer/types/msgs.go, x/executionlayer/types/types_test.go, x/executionlayer/types/validator_test.go
Do not use ValAddress in friday.
Feat:
- Need to change AccAddress type.
- clif will be used accaddress or nameservice. (do not need to use pubkey)
=> feat: remove to ValAddress

x/executionlayer/abci.go, x/executionlayer/alias.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/root.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/client/rest/rest.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/querier.go, x/executionlayer/types/codec.go, x/executionlayer/types/key.go, x/executionlayer/types/msgs.go, x/executionlayer/types/query.go, x/executionlayer/types/validator.go, x/executionlayer/types/validator_test.go
Update
--
- add to edit validator
- add to query about validator
- add to rest about validator
- refactoring unuse valpubkey in validator
Review
--
- cli test
>- `clif hdac edit-validator --wallet alsa --moniker validator`
>- `clif hdac validator --wallet alsa`
>- `clif hdac validator`
- For rest test `clif rest-server`
>- Query All Validator : GET `http://localhost:1317/contract/validators`
>- Query Validdator : GET `http://localhost:1317/contract/validators?address=friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm`
>- Create Validator : PUT `http://localhost:1317/contract/validators`
>- Edit Validator : POST `http://localhost:1317/contract/validators`
=> feat: add to edit-validator

x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/client/rest/rest.go, x/executionlayer/client/util/util.go, x/nickname/client/rest/rest.go
* `base_req` JSON key category rebirthed
1. Install [Postman](https://www.postman.com/)
1. Launch `nodef start` & `clif rest-server`
1. Test the endpoints below
```json
{
"base_req": {
"chain_id": "testnet",
"gas": "20000000",
"memo": "",
"from": "princesselsa"
},
"recipient_address_or_nickname":"friday1y2dx0evs5k6hxuhfrfdmm7wcwsrqr073htghpv",
"amount":"1000000",
"fee": "100000000"
}
```
```json
{
"base_req": {
"chain_id": "testnet",
"gas": "20000000",
"memo": "",
"from": "princesselsa"
},
"fee": "100000000",
"amount":"1000000"
}
```
```json
{
"base_req": {
"chain_id": "testnet",
"gas": "20000000",
"memo": "",
"from": "princesselsa"
},
"cons_pub_key":"fridayvalconspub16jrl8jvqq9cj7569gec8sd6dv4e4w46g25uk7vm52fpk6nfn23p5zv60xekxuse3df39sjz4g9d92nfc0f3rs3ec2fpxxum9wej52428w968xwzww9erw53ng5u …
```
=> Rollbacked to nested JSON form with "base_req" keyword

go.mod, go.sum, x/executionlayer/client/cli/tx.go, x/executionlayer/handler.go, x/executionlayer/keeper_test.go, x/executionlayer/test_common.go, x/executionlayer/types/msgs.go
- using args instead of direct abi
- support to json args in custom contract
>````[{"name":"amount","value":{"int_value":123456}},{"name":"fee","value":{"int_value":54321}}]````
>- ~~Becaful json variable name, google protobuf using camelCase..~~ support all
~~P.S. If merged https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/9, I'll change go.mod.~~ v0.2.0
=> feat: support to json args

go.mod, go.sum, scripts/install_casperlabs_ee.sh, x/executionlayer/client/cli/tx.go, x/executionlayer/genesis.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/test_common.go, x/executionlayer/types/key.go, x/executionlayer/types/msgs.go, x/executionlayer/types/types.go, x/executionlayer/util.go
Content
--
- do not need to copy wasm anymore.
- follow up casperlabs v0.11.0
PS
--
- ~the end of https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/12, will be change go.mod~
=> feat: support stored contract

client/context/context.go, integration_tests/README.md, integration_tests/lib/cmd.py, integration_tests/lib/errors.py, integration_tests/test_multi_node_simple_cli.py, integration_tests/test_single_node_simple_cli.py, scripts/install_casperlabs_ee.sh, x/executionlayer/client/cli/flags.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/util/util.go, x/nickname/client/cli/flags.go, x/nickname/client/cli/tx.go
* Key is specified by `--wallet`, `--address`, and `--nickname` flags
* Unified that to `--from`
1. No `--from`
- Check the # of the local wallet
* If only 1, use this
* If none or multiple, raise error
1. With `--from`
- Search by following priority:
1. Local wallet alias
1. Address parsing
1. Querying to nickname module
* Modified address shipping rule in client context
* Modified key selection rule in each CLI
* Reduced recurring code and put it into util
* `clif nickname set princesselsa --from elsa`
* `clif nickname set princesselsa` if only `elsa` exists
* `clif nickname change-to princesselsa fridayxxxxxxxx... --from elsa`
* `clif hdac transfer-to princessanna 1000000 100000000 25000000 --from elsa`
* `clif hdac transfer-to princessanna 1000000 100000000 25000000` if only `elsa` …
=> Unified the getter flag of the signer's private key to "from"

integration_tests/lib/cmd.py
* Removed dummy at add-genesis-account cmd
* `make integration-tests`
* Rename or remove your `~/.clif` first
=> Removed dummy at add-genesis-account integration test cmd

go.mod, go.sum, integration_tests/lib/cmd.py, integration_tests/test_single_node_simple_cli.py, scripts/install_casperlabs_ee.sh, x/executionlayer/alias.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/root.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/client/rest/rest.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/querier.go, x/executionlayer/types/codec.go, x/executionlayer/types/msgs.go, x/executionlayer/types/query.go, x/executionlayer/types/types.go, x/executionlayer/types/validator.go, x/executionlayer/util.go
Content
--
- refactoring query
- delegate query(cli, rest)
- vote
- about integration code
Example
--
- delegate query cli
```
$ clif hdac delegator [<vaidator-address>] [--from <from>]
// The delegate info of a specific validator
$ clif hdac delegator 'fridayxxxxxxxxxxxxx'
// Quantity of each stake in a specific delegator
$ clif hdac delegator --from 'fridayxxxxxxxxxxxxx'
// Both (self delegate or The delegate quantity of a specific validator)
$ clif hdac delegator 'fridayxxxxxxxxxxxxx' --from 'fridayxxxxxxxxxxxxx'
```
- delegate query rest
```
// The delegate info of a specific validator
$ http://localhost:1317/hdac/delegator?delegator=fridayxxxxxxxxxxxxx
// Quantity of each stake in a specific delegator
$ http://localhost:1317/hdac/delegator?validator=fridayxxxxxxxxxxxxx
// Both (self …
```
=> feat: support vote and some query

go.mod, go.sum, integration_tests/lib/cmd.py, integration_tests/test_single_node_simple_cli.py, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/root.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/client/rest/rest.go, x/executionlayer/handler.go, x/executionlayer/querier.go, x/executionlayer/types/codec.go, x/executionlayer/types/msgs.go, x/executionlayer/types/query.go, x/executionlayer/types/types.go
Before
--
https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/19
Content 
--
- fixed balance route in rest
- support to claim
Example
--
- claim cli
```
$ clif hdac claim commission 0.001 80000000 --from alsa
$ clif hdac claim reward 0.001 80000000 --from alsa
```
- Get reward cli
```
$ clif hdac getreward --from alsa
```
- Get commission cli
```
$ clif hdac getcommission --from alsa
```
- claim rest
```
[POST]
$ https://localhost:1317/hdac/claim
```
- Get reward rest
```
[GET]
$ http://localhost:1317/hdac/reward?address=friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm
```
- Get commission rest
```
[GET]
$ http://localhost:1317/hdac/commission?address=friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm
```
=> feat: support to claim

integration_tests/test_multi_node_simple_cli.py, integration_tests/test_single_node_simple_cli.py, x/executionlayer/alias.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/tx.go, x/executionlayer/querier.go, x/executionlayer/types/query.go
Content
--
- Using state.Value in query result.
- hash, uref using base64
- fix to query about empty path
Example
--
- query to empty path
```
$ clif contract query address system ""
{
"account": {
"publicKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
"purseId": {
"uref": "xku1iPAAyhsmVki1Pa53VZVF/pPCT9X5QGAv69zckWg=",
"accessRights": "READ_ADD_WRITE"
},
"namedKeys": [
{
"name": "client_api_proxy",
"key": {
"hash": {
"hash": "gugAzkxGTdR7iT2otcj6XG61l2QZ6FctybKFZaVFX+Y="
}
}
},
{
"name": "mint",
"key": {
"uref": {
"uref": "w6B2vpJyVZhMbg0Sglbq1bNBiUh0Js4apSv6pQzw/dk=",
"accessRights": "READ_ADD_WRITE"
}
}
},
{
"name": "pos",
"key": {
"uref": {
"uref": "5rixHWC5pAT9MnzofTEOls2CvqklMcNP8tZbw0eQiIk=",
"accessRights": "READ_ADD_WRITE"
}
}
}
],
"associatedKeys": [
{
"publicKey": …
```
=> refactor: query result format

integration_tests/lib/cmd.py, integration_tests/test_single_node_simple_cli.py, types/address.go, types/address_test.go, types/config.go, x/executionlayer/alias.go, x/executionlayer/client/cli/query.go, x/executionlayer/client/cli/tx.go, x/executionlayer/client/rest/msgCreator.go, x/executionlayer/client/rest/msgCreator_test.go, x/executionlayer/client/rest/rest.go, x/executionlayer/client/util/util.go, x/executionlayer/handler.go, x/executionlayer/keeper_test.go, x/executionlayer/querier.go, x/executionlayer/types/codec.go, x/executionlayer/types/key.go, x/executionlayer/types/msgs.go, x/executionlayer/types/query.go, x/executionlayer/util.go
* REST `Contract Run` will be tested in next PR, due to injection hardness of hexed WASM binary (REST CI test)
* ~~One more update is needed after @slave5vw 's https://github.com/hdac-io/friday/pull/122 is merged~~ Merged
* ~~Will add the test with lacking gas and check the tx fails or not (https://github.com/hdac-io/friday/pull/120)~~ Added but marked as skip. Will be activated at **https://github.com/hdac-io/friday/pull/120**
* ~~Need a one more work for replacing vote result from hash to friday address~~ Marked as known issue https://github.com/hdac-io/friday/issues/123
* Uref: `fridaycontracturef1v4xev2kdy8hkzvwcadk4a3872lzcyyz8t44du5z2jhz636qduz3sf9mf96`
* Hash: `fridaycontracthash1dl45lfet0wrsduxfeegwmskmmr8yhlpk6lk4qdpyhpjsffkymstq6ajv0a `
```bash
clif contract run hash \ …
```
=> Introduction bech32fied contract address and its related push

integration_tests/test_single_node_simple_cli.py, x/executionlayer/handler.go, x/executionlayer/types/msgs.go
- As `ContractAddress` types Interface
- In unmarshaling phase, it has error
- Use string and convert `ContractAddress` in handler
- Cannot send Uref address due to protobuf type issue
- Duplicated `Key_Uref` type and 2nd `Key_Uref` has no `isKey_Value()`
- Other types are classified with underscore (Hash, Local)
- Redundant code in handler
- Will be modified at next version (When `Key_Uref` is utilized)
=> Resolve JSON unmarshaling issue when send vote tx with REST

.travis.yml, README.md, scripts/install_casperlabs_ee.sh
Since we are currently not supporting AssemblyScript contract,
remove install dependency on node.
=> build: remove node install in ci

integration_tests/test_single_node_simple_cli.py, types/block.go, x/executionlayer/abci.go, x/executionlayer/genesis.go, x/executionlayer/handler.go, x/executionlayer/keeper.go, x/executionlayer/keeper_test.go, x/executionlayer/querier.go, x/executionlayer/test_common.go, x/executionlayer/types/key.go
- using new key in protocol version
- protocol version only call in begin block
=> refactor: delete to unnecessary marshalling

x/executionlayer/handler.go, x/executionlayer/util.go, x/executionlayer/util_test.go
* User can use friday-prefixed address into JSON parameter
**As-is of input parameter**
No conversion into EE-understandable style. Developer should encode the parameter themselves when the type of the parameter is one of `PublicKey`, `URef`, `Hash`, and so on.
```go
`[{"name":"method","value":{"cl_type":{"simple_type":"STRING"},"value":{"str_value":"set_swap_hash"}}},` +
`{"name":"hash","value":{"cl_type":{"simple_type":"KEY"},"value":{"key":{"hash":{"hash":"TfzAEiIJa0S82fxv43oS0MFLuo8oFS22CZtBc5EYlXY="}}}}},` +
`{"name":"uref","value":{"cl_type":{"simple_type":"KEY"},"value":{"key":{"uref":{"uref":"EDuWTfN9+kQ4BW7BZ+O7yf+zA7pIT+0FkJUrvbwzJiU="}}}}},` +
`{"name":"address","value":{"cl_type":{"list_type":{"inner":{"simple_type":"U8"}}},"value":{"bytes_value":"tTRwYic89GpaB72d8igFHzIZwOMZYI …
```
=> Replace from bech32 parameter into base64 in custom contract run

server/util.go
`swap` WASM takes 3.x MiB.
I raised the capacity enough, to 5 MiB
=> fix: change max tx bytes to 5MiB for swap contract

x/executionlayer/client/rest/msgCreator.go, x/executionlayer/types/query.go
* Struct of `get balance` and `get stake` are same
* In REST call, unmarshaled JSON changed into balance query only
* Modified JSON descriptor
* Avoid type confusing
Tested at https://travis-ci.org/github/psy2848048/hdacpy , `test02_rest_bond_and_unbond`
Currently marked as fail but it is rounding issue
=> Changed JSON descriptor of balance & stake querying
