hdac-io/friday

- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/client/rest/msgCreator_test.go
- x/nickname/client/rest/rest.go
* Added fee in bonding/unbonding
* Aligned gas and gas_price
This is same change of #57
> fix: align REST parameters for fixing #55

- x/executionlayer/abci.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/types/msgs.go
- chage to using common execute.
- add to execute log
- fixed power caculation error
> refator: Restructuring between keeper, handler and abci

- .gitignore
- .travis.yml
- Makefile
- integration_tests/lib/cmd.py
- integration_tests/lib/errors.py
- integration_tests/requirements.txt
- integration_tests/test_single_node_simple_cli.py
- scripts/travis_ci_prerequisites.sh
* Applied `pytest`
* Wrapped CLIs by python subprocess. It covers:
* Simple one time execution
* Multiple CLI interaction
* Daemon
* Execute `pip3 install -r integration_tests/requirements`, then execute `cd integration_tests && pytest`
* @slave5vw This boilerplate will be applied to tendermint too. Your confirmation is necessary.
* Skipped `bonding/unbonding` and `create-validator`. Will be added proper testing criteria more than sending tx and checking successful.
> Initial struct of python integration test

- integration_tests/test_single_node_simple_cli.py
* Added simple bonding/unbonding test
* Enhanced text output of tests, more than the past
* Go to the bottom of the code and check the stdout lines whether it is good or not.
> tests: added simple bonding/unbonding tests

- LICENSE
- README.md
Now we are applying document architecture and moving contents to official document page.
So I remove redundant existing contents and generalize the README.md file, initially.
see this form.
https://github.com/hdac-io/friday/blob/75977bc1e7e62f3d896cf8bb8fbf0b363e33a8ac/README.md
> generalize README.md file.

- .gitignore
- README.md
- cmd/clif/main.go
remove redundant cosmos cli commands.
you can check it to
```sh
$ clif
$ clif query
$ clif tx
```
> cli commands cleanup

- .gitignore
- README.md
- cmd/clif/main.go
remove redundant cosmos cli commands.
> master merge: cli commands cleanup 

- .travis.yml
- go.mod
- go.sum
- integration_tests/multinode_test_setup.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- x/executionlayer/client/cli/tx.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/keeper_test.go
- x/executionlayer/test_common.go
- x/executionlayer/types/msgs.go
- support to v0.14.0 in casperlabs
- apply to conv_rate
- Integration test (http://132.145.81.228:8080/job/00_CI%20multinode%20test/78/)
> feat: support to v0.14.0

- integration_tests/multinode_test_setup.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/cli/tx.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/client/rest/msgCreator_test.go
- x/executionlayer/client/util/util.go
- x/executionlayer/client/util/util_test.go
- apply to hdac unit in hdac cli(transfer, bond, unbond, getbalnace)
> feat: apply to hdac unit in hdac cli

- .travis.yml
- go.mod
- go.sum
- integration_tests/multinode_test_setup.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/cli/tx.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/client/rest/msgCreator_test.go
- x/executionlayer/client/util/util.go
- x/executionlayer/client/util/util_test.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/keeper_test.go
- x/executionlayer/test_common.go
- x/executionlayer/types/msgs.go
- support v0.14.0
- apply to conv_rate
- apply to Hdac & bigsun in cli
> feat: support v0.14.0

- integration_tests/lib/cmd.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
Number conversion in integration test
1. CI test result
1. Multinode test: http://132.145.81.228:8080/job/00_CI%20multinode%20test/82/
> Number conversion in integration test

- integration_tests/lib/cmd.py
- integration_tests/multinode_test_setup.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
* Fix # of token & staking for supporting Hdac & Bigsun unit
* Run multinode test http://132.145.81.228:8080/job/00_CI%20multinode%20test/91/
> Fix multinode testcode supporting updated decimal digits features

- go.mod
- go.sum
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/keeper_test.go
- x/executionlayer/test_common.go
- using github.com/hdac-io/casperlabs-ee-grpc-go-util v0.4.2
[Multinode test](http://132.145.81.228:8080/job/00_CI%20multinode%20test/95/)
> refactor: stored value

- integration_tests/lib/cmd.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- x/executionlayer/client/cli/root.go
- x/executionlayer/client/cli/tx.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/client/rest/msgCreator_test.go
- x/executionlayer/client/rest/rest.go
- x/executionlayer/handler.go
- x/executionlayer/resources/manifest.toml
- x/executionlayer/types/codec.go
- x/executionlayer/types/genesis.go
- x/executionlayer/types/msgs.go
- x/executionlayer/types/types.go
- add to cli & rest about delegate
- change system contract to hdac_mint and pop
Test
--
- delegate
```
$ clif hdac delegate friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm 1 0.002 30000000 --from enna
$ POST /hdac/delegate
{
"base_req": {
"chain_id": "testnet",
"gas": "30000000",
"memo": "",
"from": "<address_or_nickname>"
},
"validator_address": "friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm",
"fee": "0.002",
"amount":"1000000"
}
```
- undelegate
```
$ clif hdac undelegate friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm 1 0.002 30000000 --from enna
$ POST /hdac/undelegate
{
"base_req": {
"chain_id": "testnet",
"gas": "30000000",
"memo": "",
"from": "<address_or_nickname>"
},
"validator_address": "friday135260rslw2gkhpph2gjclm5zvvaeaf9qw7tknm",
"fee": "0.002",
"amount":"1000000"
}
```
- …
> feat: support to delegate, undelegate and redelegate

- x/executionlayer/abci.go
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/genesis.go
- x/executionlayer/keeper.go
- x/executionlayer/keeper_test.go
- x/executionlayer/module.go
- x/executionlayer/querier.go
- x/executionlayer/test_common.go
- x/executionlayer/types/genesis.go
- x/executionlayer/types/key.go
- x/executionlayer/types/query.go
- x/executionlayer/types/types.go
- x/executionlayer/types/validator.go
Content
--
- Support to export info about account & validator info
- Change ee-state management method from blockhash to height
Example
--
```
$ nodef export --height 5 --for-zero-height >> ~/.nodef/config/genesis.json
```
> feat: export

- cmd/nodef/replay.go
- go.mod
- go.sum
- integration_tests/lib/cmd.py
- integration_tests/test_multi_node_simple_cli.py
- integration_tests/test_single_node_simple_cli.py
- server/start.go
- server/tm_cmds.go
- x/genutil/utils.go
* Wait 18 sec per tx
* 10^-3 dimensioned fee
* Just send kill and not check after
* Wait 6 sec per tx
* 10^-2 dimensioned fee
* Send kill signal to daemon and check whether it really is in dead or not
> Send kill signal to daemon and check whether it really is in dead or not

- .travis.yml
- cmd/nodef/genesiscmd.go
- go.mod
- go.sum
- integration_tests/lib/cmd.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- tests/resources/executionlayer/genesis/manifest.toml
- tests/resources/executionlayer/genesis/standard_payment_install.wasm
- x/executionlayer/abci.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/configuration/chainspec.go
- x/executionlayer/configuration/chainspec_test.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/querier.go
- x/executionlayer/resources/manifest.toml
- x/executionlayer/test_common.go
- x/executionlayer/types/genesis.go
Status
--
Pending https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/21
Content
--
- add to state info in export & import 
- using ctx.BlockHeight instead of variable height.
- support to casperlabs v0.18.1
> feat: support to state export

- integration_tests/test_single_node_simple_cli.py
- x/executionlayer/handler.go
- When execution-engine execution error, change from valid-tx to invalid-tx.
- change to integration test parameter.
> feat: change to gas consumption policy

- .travis.yml
- cmd/nodef/genesiscmd.go
- go.mod
- go.sum
- integration_tests/lib/cmd.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- tests/resources/executionlayer/genesis/manifest.toml
- tests/resources/executionlayer/genesis/standard_payment_install.wasm
- x/executionlayer/abci.go
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/configuration/chainspec.go
- x/executionlayer/configuration/chainspec_test.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/keeper_test.go
- x/executionlayer/module.go
- x/executionlayer/querier.go
- x/executionlayer/resources/manifest.toml
- x/executionlayer/test_common.go
- x/executionlayer/types/genesis.go
- x/executionlayer/types/key.go
- x/executionlayer/types/query.go
- x/executionlayer/types/types.go
- x/executionlayer/types/validator.go
PR the master after rebase the existing `features/export` branch
> feat: export & casperlabs v0.18.1

- go.mod
- go.sum
- integration_tests/test_multi_node_simple_cli.py
connected tendermint pr # 23(https://github.com/hdac-io/tendermint/pull/23).
passed multi node ci by friday and tendermint.
> Private/jiyong fix ApplyBlock redirection in tm

- go.mod
- go.sum
- x/genutil/client/cli/init.go
passed multi node ci by tendermint and friday.
plz review https://github.com/hdac-io/tendermint/pull/25 together
> feat: apply TimeoutCommit

- go.mod
- go.sum
- scripts/install_casperlabs_ee.sh
- x/executionlayer/abci.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/querier.go
Content
--
- using grpc step
P.S.
--
- Pending https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/22
> feat: using grpc step

- integration_tests/lib/cmd.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- x/executionlayer/handler.go
- x/executionlayer/querier.go
- x/executionlayer/types/query.go
- x/executionlayer/types/validator.go
Content
--
- vote query using bech
- fix vote argument
P.S.
--
- Pending https://github.com/hdac-io/CasperLabs/pull/28
> feat: vote using bech

- x/executionlayer/alias.go
- x/executionlayer/genesis.go
- x/executionlayer/handler.go
- x/executionlayer/keeper.go
- x/executionlayer/types/errors.go
- x/executionlayer/types/key.go
Instead of https://github.com/hdac-io/friday/pull/144
> feat: add to validation when create validator

- go.mod
- go.sum
- integration_tests/lib/cmd.py
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- x/executionlayer/alias.go
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/cli/root.go
- x/executionlayer/client/rest/msgCreator.go
- x/executionlayer/client/rest/msgCreator_test.go
- x/executionlayer/client/rest/rest.go
- x/executionlayer/handler.go
- x/executionlayer/querier.go
- x/executionlayer/types/query.go
Pending : https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/25
Will be need to change module tag.
Content
--
- clif hdac getstake --from alsa
- clif hdac getvote --from alsa
- clif hdac getvote fridaycontracthash~~~
- clif hdac getvote fridaycontracturef~~~
- GET /hdac/stake?address=friday~~
- GET /hdac/vote?address=friday~~~
- GET /hdac/vote?dapp=fridaycontracthash~~
- GET /hdac/vote?dapp=fridaycontracturef~~
P.S.
- For unbonding delay, will be need to change ci & intengration test.
https://github.com/hdac-io/CasperLabs/commit/0a928aad5ede6b7dbadc42dd858b6b740a4deba4
> feat: divide bond & unbond

- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
Unbond, redelegation and undelegate 2-day delay apply.
Pending https://github.com/hdac-io/friday/pull/151
> feat: apply to unbonding delay

- go.mod
- go.sum
- integration_tests/test_single_node_simple_cli.py
- scripts/install_casperlabs_ee.sh
- types/context.go
- x/executionlayer/abci.go
- x/executionlayer/handler.go
- x/executionlayer/querier.go
fix query commission and reward
add block height to step request
dependent with https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/28
> follow execution engine

- go.mod
- go.sum
- scripts/install_casperlabs_ee.sh
- x/executionlayer/abci.go
- x/executionlayer/client/cli/query.go
- x/executionlayer/client/rest/rest.go
- x/executionlayer/genesis.go
- x/executionlayer/querier.go
~Pending~
--
~https://github.com/hdac-io/casperlabs-ee-grpc-go-util/pull/30~
Content
--
- Using CLInstanceValue instead of state.Value
- fixed rest stake query
- fixed delegate bug( Fixes #156 )
> Fixed bug & Using CLInstanceValue

- x/bank/module.go
- x/distribution/module.go
- x/gov/module.go
- x/mint/module.go
- x/slashing/module.go
- x/staking/module.go
- x/supply/module.go
* Bank
* Distribution
* Gov
* Mint
* Slashing
* Staking
* Supply
> Disable unused REST route
